PerfectCRM/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls')),
    path('sales/', include('sales.urls')),
    path('myadmin/', include('myadmin.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
]

crm/urls.py
from django.contrib import admin
from django.urls import path,include
from crm import views
urlpatterns = [
    path('index/', views.index),
    path('testindex/', views.forms_test),
    path('acc_login/', views.acc_login),
    path('acc_logout/', views.acc_logout,name="acc_logout"),
    path('create_student/<int:customer_id>', views.create_student,name="create_student"),
    path('<str:table_name>/<str:id>/enrollment/', views.enrollment),
    path('<str:table_name>/<str:id>/enrollment/confirm/', views.enrollmentConfirm),
    path('customer/<str:id>/registration/<str:str>', views.stu_registration,name="stu_registration"),


]

student/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from student import views
urlpatterns = [
    path('student_index/', views.student_index,name='student_index'),

    path('<str:enrollment_id>/course_record/', views.course_record,name='course_record'),

    path('<str:studyrecord_id>/homework/down/<str:name>', views.hm_file_down,name='homework_down'),
    re_path(r'\d+/course_record/(?P<studyrecord_id>\w+)/homework$',views.stu_submit_homework,name='stu_submit_homework'),

]

crm/models.py
from django.db import models
from django.contrib.auth.models import User#django自带的验证
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe


# Create your models here.
class Customer(models.Model):
    '''客户信息表'''
    name = models.CharField(max_length=32,default='',verbose_name='名字')
    qq = models.CharField(max_length=64,unique=True)
    phone=models.CharField(max_length=64,blank=True,null=True,verbose_name='手机号码')
    qq_name=models.CharField(max_length=64,blank=True,null=True,verbose_name='qq名字')
    source_choice=((0,'转介绍'),
                    (1,'qq群'),
                    (2,'官网'),
                    (3,'百度推广'),
                    (4,'51CTO'),
                    (5,'知乎'),
                    (6,'市场推广'),

                    )
    status_choices=((0,"未报名"),#初始状态
                    (1,"等待填写报名信息"),#销售拉到客户生成报名信息表
                    (2,"等待审核"),#学员填写好了报名信息,等待销售审核信息
                    (3,"等待缴费"),#销售审核完信息,等待缴费
                    (4,"学员"),#财务确认缴费

                    )
    status=models.SmallIntegerField(choices=status_choices,default=0,verbose_name='报名状态')
    source = models.SmallIntegerField(choices=source_choice,verbose_name='来源于')
    referral_from = models.CharField(verbose_name='转介紹人',max_length=64,blank=True)
    consult_course = models.ForeignKey('Course',verbose_name='咨询课程',on_delete=models.CASCADE)
    content = models.TextField(verbose_name="咨询详情")
    consultant=models.ForeignKey("UserProfile",on_delete=models.CASCADE,verbose_name='接待人')
    memo=models.TextField(null=True,blank=True,verbose_name='备注')
    tag=models.ManyToManyField('Tag',null=True,blank=True,verbose_name='标签')
    data=models.DateTimeField(auto_now_add=True,verbose_name='时间')
    id_num=models.CharField(max_length=64,null=True,blank=True,verbose_name="身份证")
    email=models.EmailField(max_length=64,null=True,blank=True,verbose_name="常用邮箱")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="客户表"

class Tag(models.Model):
    '''标签'''
    name=models.CharField(unique=True,max_length=32)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="标签"

class CustomFollowUp(models.Model):
    '''客户跟进表'''
    customer=models.ForeignKey("Customer",on_delete=models.CASCADE,verbose_name='客户名')
    content=models.TextField(verbose_name="跟进内容")
    consultant=models.ForeignKey('UserProfile',on_delete=models.CASCADE,verbose_name='跟进人')
    itention_choice=((0,'2周内报名'),
                     (1,'一月内报名'),
                     (2,'无报名计划'),
                     (3,'已在其他机构报名'),
                     (4,'已报名'),
                     (5,'已拉黑'),
                     )
    followup_times=models.PositiveSmallIntegerField(verbose_name='跟进次数',default=1)
    itention=models.SmallIntegerField(choices=itention_choice,verbose_name='计划')
    data=models.DateTimeField(auto_now_add=True,verbose_name='时间')
    def __str__(self):
        return '客户:%s第%s次跟进'%(self.customer,self.followup_times)
    class Meta:
        verbose_name="客户跟进表"
        unique_together=('customer','followup_times')

class CourseRecord(models.Model):
    '''上课记录'''
    clazz=models.ForeignKey('Clazz',on_delete=models.CASCADE,verbose_name='班级')
    has_homework=models.BooleanField(default=True,verbose_name='是否有作业')
    home_title=models.CharField(max_length=32,verbose_name='作业的标题')
    outline=models.CharField(max_length=128,verbose_name="本节课的大纲")
    homework=models.TextField(null=True,blank=True,verbose_name='作业的内容')
    day_num=models.PositiveSmallIntegerField(verbose_name="第几节课")
    teachers=models.ForeignKey("UserProfile",on_delete=models.CASCADE,verbose_name='上课老师')
    data=models.DateField(auto_now_add=True,verbose_name='上课时间')
    def __str__(self):
        return '%s的第%s节课程记录'%(self.clazz,self.day_num)
    class Meta:
        unique_together=("clazz",'day_num')


        verbose_name = "上课记录"

class StudyRecord(models.Model):
    '''学习记录'''
    student=models.ForeignKey('UserProfile',on_delete=models.CASCADE,verbose_name='学生姓名')
    course_record=models.ForeignKey('CourseRecord',on_delete=models.CASCADE,verbose_name='上课记录')
    attendance_choice=((0,'已签到'),
                       (1,'迟到'),
                       (2,'缺勤'),
                       (3,'早退'),
                       (4,'请假'),
                       )
    attendance=models.PositiveSmallIntegerField(choices=attendance_choice,default=0,verbose_name='考勤')
    score_choice=((100,"A+"),
                  (90,"A"),
                  (80,"B"),
                  (60,"C"),
                  (40,"D"),
                  (-50,"E"),
                  (-100,"copy"),
                  (0,"N/A"),

                    )
    has_submit_homework=models.BooleanField(default=False,verbose_name='是否提交作业')
    score=models.SmallIntegerField(choices=score_choice,default=0,verbose_name='成绩')
    memo=models.TextField(blank=True,null=True,verbose_name='本节课备注')
    data=models.DateTimeField(auto_now_add=True,verbose_name='学习时间')
    def __str__(self):
        return "学生%s的%s"%(self.student,self.course_record,)

    class Meta:
        verbose_name="学习记录"
        unique_together=('student','course_record')

class Course(models.Model):
    '''课程表'''
    name=models.CharField(max_length=64,unique=True,verbose_name='课程名字')
    price=models.PositiveSmallIntegerField(verbose_name='课程价格')
    period=models.PositiveSmallIntegerField(verbose_name="课程周期")

    outline = models.TextField(verbose_name='课程大纲')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="课程表"

class Brach(models.Model):
    '''校区'''
    name=models.CharField(max_length=64,unique=True)
    addr=models.CharField(max_length=128)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="校区"

class Clazz(models.Model):
    '''班级表'''
    brach=models.ForeignKey("Brach",on_delete=models.CASCADE,verbose_name='校区')
    contract=models.ForeignKey("Contract",on_delete=models.CASCADE,verbose_name="合同")
    course=models.ForeignKey("Course",on_delete=models.CASCADE,verbose_name='课程名字')
    semester=models.PositiveSmallIntegerField(verbose_name='学期')
    teachers=models.ManyToManyField('UserProfile',verbose_name='班级老师')
    type_choice=((0,'面授(脱产)'),
                 (1,"面授(周末)"),
                 (2,"面授(全期)"),
                 (3,"网络"),
                 )
    type=models.SmallIntegerField(choices=type_choice)
    start_data=models.DateField(verbose_name='开班日期')
    end_data=models.DateField(verbose_name='结业日期',blank=True,null=True)

    def __str__(self):
        return "%s-%s课程-%s期"%(self.brach,self.course,self.semester)
    class Meta:
        unique_together=("brach",'course','semester')
        verbose_name="班级"

class Enrollment(models.Model):

    '''报名表'''
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE,verbose_name='客户')
    enrolled_clazz=models.ForeignKey('clazz',verbose_name='所报班级',on_delete=models.CASCADE)
    consultant=models.ForeignKey('UserProfile',verbose_name="签单人",on_delete=models.CASCADE)
    contract_agreed=models.BooleanField(default=False,verbose_name="学员同意")
    consultant_approval=models.BooleanField(default=False,verbose_name="审核人已审核")
    data=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '客户%s的%s课程报名表'%(self.customer,self.enrolled_clazz)
    class Meta:
        unique_together=('customer','enrolled_clazz')


        verbose_name = "报名表"

class Payment(models.Model):
    '''缴费表'''
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE)
    pay_course=models.ForeignKey("Course",verbose_name='缴费课程',on_delete=models.CASCADE)
    amount=models.PositiveIntegerField(verbose_name="已交数额",default=500)
    consultant=models.ForeignKey('UserProfile',verbose_name="协助缴费人",on_delete=models.CASCADE)
    data=models.DateTimeField(auto_now_add=True)
    pay_status_choice=((0,'未缴费'),
                       (1,"已缴纳部分金额"),
                       (2,"已缴费"),
                       )
    pay_status=models.SmallIntegerField(choices=pay_status_choice,default=0)
    def __str__(self):
        return "<%s %s>"%(self.customer,self.pay_course)
    class Meta:
        unique_together=('customer','pay_course')
        verbose_name="缴费记录"

class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, stu_customer=None, password=None, ):
        """
        Creates and saves a User with the given email,  and password.
        """
        if not email:
            raise ValueError('Users must have an email addres')

        user = self.model(
            email=self.normalize_email(email),
            name=name,

            stu_customer=stu_customer,
        )

        user.set_password(password)

        self.is_active=True
        user.save(using=self._db)
        return user

    def create_superuser(self, email,name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class UserProfile(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(
        verbose_name='邮箱',
        max_length=255,
        unique=True,

    )
    password = models.CharField(_('password'), max_length=128,help_text=mark_safe("<a href='../password_reset'>点我改密码</a>"))
    name=models.CharField(max_length=32,verbose_name='用户姓名')
    stu_customer=models.OneToOneField("Customer",null=True,blank=True,verbose_name='用户对应的客户',on_delete=models.CASCADE,help_text='只有交费成功的用户能够注册')
    role=models.ManyToManyField("Role",verbose_name='角色')
    is_active = models.BooleanField(default=True,verbose_name='是否活跃')
    is_admin = models.BooleanField(default=False,verbose_name='是否是管理员')

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render,HttpResponse
from django.db.models import Avg,Max,Min,Sum
from crm import models
from django.http import FileResponse
import os
from PerfectCRM import settings
from django.contrib.auth.decorators import login_required
from crm.permission.permission_handle import check_permission

# Create your views here.
@login_required
def home_work_url(req,studyrecord_obj):
    '''获取学生作业路径'''

    stuhomework_base_dir = '%s{sep}%s{sep}第%s节{sep}%s' % (settings.STU_HOMEWORK_DATA_URL,
                                              studyrecord_obj.course_record.clazz,
                                              studyrecord_obj.course_record.day_num,
                                              req.user.name,
                                              )
    stuhomework_base_dir=stuhomework_base_dir.format(sep=os.sep)

    if os.path.exists(stuhomework_base_dir):
        return (stuhomework_base_dir,True)
    else:
        return (stuhomework_base_dir,False )
@login_required
def student_index(req):

    enrollments=req.user.stu_customer.enrollment_set.all()

    return render(req,'student/stu_index.html',{'enrollments':enrollments})
@login_required
def course_record(req,enrollment_id):


    # enrollment = req.user.stu_customer.enrollment_set.get(id=enrollment_id)


    return render(req, 'student/class_record.html', )
# @check_permission
@login_required
def stu_submit_homework(req,studyrecord_id):

    studyrecord_obj=models.StudyRecord.objects.get(id=studyrecord_id)
    homework_names = []
    if req.is_ajax():
        # base/班级/第几节/学生/xx.zip

        if not home_work_url(req,studyrecord_obj)[1]:

            os.makedirs(home_work_url(req,studyrecord_obj)[0], exist_ok=True)
            for k,v in req.FILES.items():
                with open('%s/%s'%(home_work_url(req,studyrecord_obj)[0],v.name),'wb') as f:
                    for chunk in v.chunks():
                        f.write(chunk)

            studyrecord_obj.has_submit_homework = True
            studyrecord_obj.save()


    elif req.method=="GET":
        if home_work_url(req,studyrecord_obj)[1]:
            homework_names=os.listdir(r'%s'%home_work_url(req,studyrecord_obj)[0])

    return render(req,"student/homework.html",{'studyrecord_obj':studyrecord_obj,"homework_names":homework_names,})

@login_required
def hm_file_down(request,studyrecord_id,name):

    studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
    home_work_url(request, studyrecord_obj)[0]


    file=open(home_work_url(request, studyrecord_obj)[0]+os.sep+name,'rb')
    response =FileResponse(file)
    response['Content-Type']='application/octet-stream'
    response['Content-Disposition']='attachment;filename="%s"'%name
    return response

templates/student/class_record.html
{% extends 'blank.html' %}
{% load stu_tags %}
{% block row-menus %}
    <ol class="breadcrumb">
     <li><i class="fa fa-home"></i><a href="{% url 'student_index' %}">Home</a></li>
    <li><i class="fa fa-book"></i>课程详情</li>
    </ol>
{% endblock  %}
{% block page-content %}
    <div class="col-sm-12">
          <section class="panel">
              <header class="panel-heading">
                  学生信息
              </header>
              <table class="table table-hover">
                  <thead>
                  <tr>
                      <th>#</th>

                      <th>课程名字</th>
                      <th>课程节数</th>
                      <th>时间</th>
                      <th>作业大纲</th>
                      <th>成绩</th>
                      <th>签到状态</th>
                      <th>作业</th>



                  </tr>
                  </thead>
                  <tbody>

                  {% for studyrecord in request.user.studyrecord_set.all %}
                      <tr>
                          <td>xx</td>
                          <td>{{ studyrecord.course_record.clazz }}</td>
                          <td>第{{ studyrecord.course_record.day_num }}节</td>
                          <td>{{ studyrecord.data }}</td>
                          <td>{{ studyrecord.course_record.outline }}</td>
                          <td>{{ studyrecord.get_score_display }}</td>
                          <td>{{ studyrecord.get_attendance_display }}</td>

                          {% if studyrecord.course_record.has_homework  %}



                                {% if studyrecord.has_submit_homework  %}

                                    <td><a href="{{ studyrecord.id }}/homework">查看作业</a></td>
                                {% else %}

                                    <td><a href="{{ studyrecord.id }}/homework">交作业</a></td>
                                {% endif %}
                          {% else %}
                              <td>没有作业!!!</td>
                          {% endif %}

                          
                      </tr>
                  {% endfor %}




                  <tr>
                      <td>123</td>
                      <td colspan="5">Larry the Bird</td>
                      <td>@twitter</td>

                  </tr>

                  </tbody>
              </table>
          </section>
    </div>

{% endblock %}

</body>
</html>

templates/student/homework.html
{% extends 'blank.html' %}
{% load stu_tags %}
{% block cus-css %}
    <link rel="stylesheet" href="/static/plugin/dropzone.css">
{% endblock %}
{% block row-menus %}
    <ol class="breadcrumb">
    <li><i class="fa fa-home"></i><a href="{% url 'student_index' %}">首页</a></li>
    <li><i class="fa fa-book"></i><a href="../">课程详情</a></li>
    <li><i class="fa fa-edit"></i>我的作业</li>
    </ol>
{% endblock  %}

{% block page-content %}
    <div class="col-sm-12">
        <div class="panel panel-info">
              <div class="panel-heading text-center ">
                  <h4>

                      {{ studyrecord_obj.course_record.clazz }} 第 {{ studyrecord_obj.course_record.day_num }} 节作业内容

                  </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse in">
                  <div class="panel-body">
                       <p>作业标题:{{ studyrecord_obj.course_record.home_title }}</p>
                      {{ studyrecord_obj.course_record.homework }}
                  </div>
              </div>
        </div>



        <div  class=" panel panel-success">
            <div class="panel-heading">我的作业</div>
                  {% if studyrecord_obj.has_submit_homework %}
                      {% if homework_names %}
                          <ul>{% for name in homework_names  %}
                             <li><a href="{% url 'homework_down' studyrecord_obj.id name%}">{{ name }}</a></li>
                          {% endfor %}
                          </ul>


                      {% else %}
                          <p>作业可能被异常删除,请联系老师</p>
                      {% endif %}
                  {% else  %}


                      <div id='myId' class="dropzone panel-content"  style="height: 250px"></div>

                      <button type="button" id="sub-img" class="btn btn-xs  col-lg-pull-12">提交作业</button>
                  {% endif %}
            </div>
        </div>
    </div>

{% endblock %}


{% block script %}
    <script src="/static/plugin/dropzone.js"></script>
    <script src="/static/js/jquery.cookie.js"></script>
    <script>
        upload_status=false
        Dropzone.autoDiscover = false;
        $("#myId").dropzone({
            url: window.document.location.href,
            method: 'post',
            clickable:true,
            autoProcessQueue:false,
            acceptedFiles:".RAR,.ZIP,.CAB,.ARJ,.LZH,.ACE,.7-Zip,.TAR,.GZip,.UUE,.BZ2,.JAR,.ISO,.Z",
            filesizeBase: 1024,
            uploadMultiple: true,
            data:{'xxx':'yyy'},
            parallelUploads: 100,
            headers:{"X-CSRFToken":$.cookie("csrftoken")},
            maxFiles: 2,
            dictDefaultMessage:"请将作业以压缩格式上传,命名为班级+姓名",
            init:function () {
                this.on("addedfile", function(file) {
                     var removeButton = Dropzone.createElement("<button id='del-btn' class='btn btn-danger btn-xs'>删除文件</button>");
                     var _this = this;

                     removeButton.addEventListener("click", function(e) {

                          e.preventDefault();
                          e.stopPropagation();
                          _this.removeFile(file);
                     });
                     file.previewElement.appendChild(removeButton);

                })

                var _this = this;

                $("#sub-img").on("click", function() {
                    if (_this.files.length==1){_this.processQueue();}
                    else{alert("请上传压缩包格式的作业")}

                });

                this.on("maxfilesexceeded", function(file) { this.removeFile(file); });


                this.on("success", function(e) {
                    $("#sub-img").remove();
                    $("#del-btn").remove();



                });
            },


    });
    </script>
{% endblock %}

templates/student/stu_index.html
{% extends 'blank.html' %}
{% load stu_tags %}
{% block row-menus %}
    <ol class="breadcrumb"><li><i class="fa fa-home"></i>首页</li></ol>

{% endblock  %}
{% block left-menu %}

{% endblock  %}


{% block page-content %}
    <div class="col-sm-12">
          <section class="panel">
              <header class="panel-heading">
                  学生信息
              </header>
              <table class="table table-hover">
                  <thead>
                  <tr>
                      <th>#</th>
                      <th>课程名称</th>
                      <th>所报班级</th>
                      <th>开课日期</th>
                      <th>课程进度</th>
                      <th><i class="icon_calendar"></i>我的成绩</th>
                      <th><i class="icon_book"></i>作业管理</th>

                  </tr>
                  </thead>
                  <tbody>

                  {% for enroll_obj in enrollments %}
                      <tr>
                          <td>xx</td>
                          <td>{{ enroll_obj.enrolled_clazz.course }}</td>
                          <td>第{{ enroll_obj.enrolled_clazz.semester }}期</td>
                          <td>{{ enroll_obj.enrolled_clazz.start_data }}</td>
                          <td>已上{{ enroll_obj.enrolled_clazz.courserecord_set.all.count }}节课</td>
                          <td>{% handle_score enroll_obj %}</td>
                          <td><a href="{% url 'course_record' enroll_obj.id %}">上课记录</a></td>
                      </tr>
                  {% endfor %}




                  <tr>
                      <td>123</td>
                      <td colspan="5">Larry the Bird</td>
                      <td>@twitter</td>

                  </tr>

                  </tbody>
              </table>
          </section>
    </div>

{% endblock %}