PerfectCRM/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls')),
    path('sales/', include('sales.urls')),
    path('myadmin/', include('myadmin.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
]

crm/urls.py
from django.contrib import admin
from django.urls import path,include
from crm import views
urlpatterns = [
    path('index/', views.index),
    path('testindex/', views.forms_test),
    path('acc_login/', views.acc_login),
    path('acc_logout/', views.acc_logout,name="acc_logout"),
    path('create_student/<int:customer_id>', views.create_student,name="create_student"),
    path('<str:table_name>/<str:id>/enrollment/', views.enrollment),
    path('<str:table_name>/<str:id>/enrollment/confirm/', views.enrollmentConfirm),
    path('customer/<str:id>/registration/<str:str>', views.stu_registration,name="stu_registration"),


]

teacher/urls.py
from django.contrib import admin
from django.urls import path,include
from teacher import views
urlpatterns = [
    path('teacher_index/', views.teacher_index,name='teacher_index'),
    path('down_homework/<int:stu_record_id>', views.down_homework),
    path('teacher_courserecord/<str:class_id>/<int:stu_record_id>', views.teacher_courserecord,name='teacher_courserecord'),
    path('teacher_courserecord/<str:class_id>/add', views.teacher_courserecord_add,name='teacher_courserecord_add'),



]

crm/models.py
from django.db import models
from django.contrib.auth.models import User#django自带的验证
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe


# Create your models here.
class Customer(models.Model):
    '''客户信息表'''
    name = models.CharField(max_length=32,default='',verbose_name='名字')
    qq = models.CharField(max_length=64,unique=True)
    phone=models.CharField(max_length=64,blank=True,null=True,verbose_name='手机号码')
    qq_name=models.CharField(max_length=64,blank=True,null=True,verbose_name='qq名字')
    source_choice=((0,'转介绍'),
                    (1,'qq群'),
                    (2,'官网'),
                    (3,'百度推广'),
                    (4,'51CTO'),
                    (5,'知乎'),
                    (6,'市场推广'),

                    )
    status_choices=((0,"未报名"),#初始状态
                    (1,"等待填写报名信息"),#销售拉到客户生成报名信息表
                    (2,"等待审核"),#学员填写好了报名信息,等待销售审核信息
                    (3,"等待缴费"),#销售审核完信息,等待缴费
                    (4,"学员"),#财务确认缴费

                    )
    status=models.SmallIntegerField(choices=status_choices,default=0,verbose_name='报名状态')
    source = models.SmallIntegerField(choices=source_choice,verbose_name='来源于')
    referral_from = models.CharField(verbose_name='转介紹人',max_length=64,blank=True)
    consult_course = models.ForeignKey('Course',verbose_name='咨询课程',on_delete=models.CASCADE)
    content = models.TextField(verbose_name="咨询详情")
    consultant=models.ForeignKey("UserProfile",on_delete=models.CASCADE,verbose_name='接待人')
    memo=models.TextField(null=True,blank=True,verbose_name='备注')
    tag=models.ManyToManyField('Tag',null=True,blank=True,verbose_name='标签')
    data=models.DateTimeField(auto_now_add=True,verbose_name='时间')
    id_num=models.CharField(max_length=64,null=True,blank=True,verbose_name="身份证")
    email=models.EmailField(max_length=64,null=True,blank=True,verbose_name="常用邮箱")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="客户表"

class Tag(models.Model):
    '''标签'''
    name=models.CharField(unique=True,max_length=32)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="标签"

class CustomFollowUp(models.Model):
    '''客户跟进表'''
    customer=models.ForeignKey("Customer",on_delete=models.CASCADE,verbose_name='客户名')
    content=models.TextField(verbose_name="跟进内容")
    consultant=models.ForeignKey('UserProfile',on_delete=models.CASCADE,verbose_name='跟进人')
    itention_choice=((0,'2周内报名'),
                     (1,'一月内报名'),
                     (2,'无报名计划'),
                     (3,'已在其他机构报名'),
                     (4,'已报名'),
                     (5,'已拉黑'),
                     )
    followup_times=models.PositiveSmallIntegerField(verbose_name='跟进次数',default=1)
    itention=models.SmallIntegerField(choices=itention_choice,verbose_name='计划')
    data=models.DateTimeField(auto_now_add=True,verbose_name='时间')
    def __str__(self):
        return '客户:%s第%s次跟进'%(self.customer,self.followup_times)
    class Meta:
        verbose_name="客户跟进表"
        unique_together=('customer','followup_times')

class CourseRecord(models.Model):
    '''上课记录'''
    clazz=models.ForeignKey('Clazz',on_delete=models.CASCADE,verbose_name='班级')
    has_homework=models.BooleanField(default=True,verbose_name='是否有作业')
    home_title=models.CharField(max_length=32,verbose_name='作业的标题')
    outline=models.CharField(max_length=128,verbose_name="本节课的大纲")
    homework=models.TextField(null=True,blank=True,verbose_name='作业的内容')
    day_num=models.PositiveSmallIntegerField(verbose_name="第几节课")
    teachers=models.ForeignKey("UserProfile",on_delete=models.CASCADE,verbose_name='上课老师')
    data=models.DateField(auto_now_add=True,verbose_name='上课时间')
    def __str__(self):
        return '%s的第%s节课程记录'%(self.clazz,self.day_num)
    class Meta:
        unique_together=("clazz",'day_num')


        verbose_name = "上课记录"

class StudyRecord(models.Model):
    '''学习记录'''
    student=models.ForeignKey('UserProfile',on_delete=models.CASCADE,verbose_name='学生姓名')
    course_record=models.ForeignKey('CourseRecord',on_delete=models.CASCADE,verbose_name='上课记录')
    attendance_choice=((0,'已签到'),
                       (1,'迟到'),
                       (2,'缺勤'),
                       (3,'早退'),
                       (4,'请假'),
                       )
    attendance=models.PositiveSmallIntegerField(choices=attendance_choice,default=0,verbose_name='考勤')
    score_choice=((100,"A+"),
                  (90,"A"),
                  (80,"B"),
                  (60,"C"),
                  (40,"D"),
                  (-50,"E"),
                  (-100,"copy"),
                  (0,"N/A"),

                    )
    has_submit_homework=models.BooleanField(default=False,verbose_name='是否提交作业')
    score=models.SmallIntegerField(choices=score_choice,default=0,verbose_name='成绩')
    memo=models.TextField(blank=True,null=True,verbose_name='本节课备注')
    data=models.DateTimeField(auto_now_add=True,verbose_name='学习时间')
    def __str__(self):
        return "学生%s的%s"%(self.student,self.course_record,)

    class Meta:
        verbose_name="学习记录"
        unique_together=('student','course_record')

class Course(models.Model):
    '''课程表'''
    name=models.CharField(max_length=64,unique=True,verbose_name='课程名字')
    price=models.PositiveSmallIntegerField(verbose_name='课程价格')
    period=models.PositiveSmallIntegerField(verbose_name="课程周期")

    outline = models.TextField(verbose_name='课程大纲')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="课程表"

class Brach(models.Model):
    '''校区'''
    name=models.CharField(max_length=64,unique=True)
    addr=models.CharField(max_length=128)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="校区"

class Clazz(models.Model):
    '''班级表'''
    brach=models.ForeignKey("Brach",on_delete=models.CASCADE,verbose_name='校区')
    contract=models.ForeignKey("Contract",on_delete=models.CASCADE,verbose_name="合同")
    course=models.ForeignKey("Course",on_delete=models.CASCADE,verbose_name='课程名字')
    semester=models.PositiveSmallIntegerField(verbose_name='学期')
    teachers=models.ManyToManyField('UserProfile',verbose_name='班级老师')
    type_choice=((0,'面授(脱产)'),
                 (1,"面授(周末)"),
                 (2,"面授(全期)"),
                 (3,"网络"),
                 )
    type=models.SmallIntegerField(choices=type_choice)
    start_data=models.DateField(verbose_name='开班日期')
    end_data=models.DateField(verbose_name='结业日期',blank=True,null=True)

    def __str__(self):
        return "%s-%s课程-%s期"%(self.brach,self.course,self.semester)
    class Meta:
        unique_together=("brach",'course','semester')
        verbose_name="班级"

class Enrollment(models.Model):

    '''报名表'''
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE,verbose_name='客户')
    enrolled_clazz=models.ForeignKey('clazz',verbose_name='所报班级',on_delete=models.CASCADE)
    consultant=models.ForeignKey('UserProfile',verbose_name="签单人",on_delete=models.CASCADE)
    contract_agreed=models.BooleanField(default=False,verbose_name="学员同意")
    consultant_approval=models.BooleanField(default=False,verbose_name="审核人已审核")
    data=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '客户%s的%s课程报名表'%(self.customer,self.enrolled_clazz)
    class Meta:
        unique_together=('customer','enrolled_clazz')


        verbose_name = "报名表"

class Payment(models.Model):
    '''缴费表'''
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE)
    pay_course=models.ForeignKey("Course",verbose_name='缴费课程',on_delete=models.CASCADE)
    amount=models.PositiveIntegerField(verbose_name="已交数额",default=500)
    consultant=models.ForeignKey('UserProfile',verbose_name="协助缴费人",on_delete=models.CASCADE)
    data=models.DateTimeField(auto_now_add=True)
    pay_status_choice=((0,'未缴费'),
                       (1,"已缴纳部分金额"),
                       (2,"已缴费"),
                       )
    pay_status=models.SmallIntegerField(choices=pay_status_choice,default=0)
    def __str__(self):
        return "<%s %s>"%(self.customer,self.pay_course)
    class Meta:
        unique_together=('customer','pay_course')
        verbose_name="缴费记录"

class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, stu_customer=None, password=None, ):
        """
        Creates and saves a User with the given email,  and password.
        """
        if not email:
            raise ValueError('Users must have an email addres')

        user = self.model(
            email=self.normalize_email(email),
            name=name,

            stu_customer=stu_customer,
        )

        user.set_password(password)

        self.is_active=True
        user.save(using=self._db)
        return user

    def create_superuser(self, email,name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class UserProfile(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(
        verbose_name='邮箱',
        max_length=255,
        unique=True,

    )
    password = models.CharField(_('password'), max_length=128,help_text=mark_safe("<a href='../password_reset'>点我改密码</a>"))
    name=models.CharField(max_length=32,verbose_name='用户姓名')
    stu_customer=models.OneToOneField("Customer",null=True,blank=True,verbose_name='用户对应的客户',on_delete=models.CASCADE,help_text='只有交费成功的用户能够注册')
    role=models.ManyToManyField("Role",verbose_name='角色')
    is_active = models.BooleanField(default=True,verbose_name='是否活跃')
    is_admin = models.BooleanField(default=False,verbose_name='是否是管理员')

teacher/models.py
from django.db import models

# Create your models here.

teacher/forms.py
from django.forms import ModelForm
from django import forms
from crm import models



class Courserecordtmodelform(ModelForm):
    def __new__(cls,*args,**kwargs):


        for k,v in cls.base_fields.items():
            if k in cls.Meta.readonly_fields:
                v.widget.attrs["class"] = "form-control disabled_field"
                v.widget.attrs["disabled"] = "disabled"
            else:
                v.widget.attrs["class"] = "form-control "


        return forms.ModelForm.__new__(cls)

    def clean_qq(self):
        if self.instance.qq!=self.cleaned_data['qq']:
            self.add_error("qq",'请不要修改不可变动字段')
        else:
            return self.cleaned_data['qq']
    def clean_consult_course(self):
        if self.instance.consult_course!=self.cleaned_data['consult_course']:
            self.add_error("consult_course",'请不要修改不可变动字段')
        else:
            return self.cleaned_data['consult_course']
    def clean_consultant(self):
        if self.instance.consultant!=self.cleaned_data['consultant']:
            self.add_error("consultant",'请不要修改不可变动字段')
        else:
            return self.cleaned_data['consultant']
    class Meta:
        model=models.CourseRecord
        fields="__all__"
        exclude=["clazz",'teachers']
        readonly_fields=['consult_course','qq','consultant']

teacher/views.py
from django.shortcuts import render,HttpResponse,redirect
from crm import models
from teacher import forms
from django.db.utils import IntegrityError

# Create your views here.
def teacher_index(req):
    class_obj_queryset=models.Clazz.objects.filter(teachers=req.user.id).all()
    print(class_obj_queryset)
    return render(req,'teacher/teacher_index.html',{'class_obj_queryset':class_obj_queryset})
def teacher_courserecord(req,class_id):
    courserecord_obj_queryset=models.CourseRecord.objects.filter(clazz=class_id).all()

    print(courserecord_obj_queryset)
    return render(req,'teacher/teacher_courserecord.html',{'courserecord_obj_queryset':courserecord_obj_queryset})

def teacher_courserecord_add(req,class_id):
    clazz_obj=models.Clazz.objects.get(id=class_id)
    error=''
    if req.method=="GET":
        RCforms=forms.Courserecordtmodelform()
        return render(req,'teacher/teacher_courserecord_add.html',{'clazz_obj':clazz_obj,'RCforms':RCforms,'error':error})
    elif req.method=="POST":

        print(req.POST)
        # second_dict=dict(req.POST)
        # second_dict['clazz']=class_id
        # second_dict['teachers']=req.user.id
        # second_dict['day_num']=1
        # print(second_dict)
        RCforms = forms.Courserecordtmodelform(req.POST)
        if RCforms.is_valid():
            RCforms.cleaned_data['clazz']=models.Clazz.objects.get(id=class_id)
            RCforms.cleaned_data['teachers']=models.UserProfile.objects.get(id=req.user.id)
            try:
                models.CourseRecord.objects.create(**RCforms.cleaned_data)
            except IntegrityError as e:
                error='添加课程天数已存在'
                return render(req, 'teacher/teacher_courserecord_add.html', {'clazz_obj':clazz_obj,'RCforms': RCforms, 'error': error})

            return redirect(req.path.replace('add',''))
        else:
            error=RCforms.errors
            return render(req, 'teacher/teacher_courserecord_add.html', {'clazz_obj':clazz_obj,'RCforms': RCforms, 'error': error})

def down_homework(req,stu_record_id):
    import os
    from PerfectCRM import settings
    from django.http import FileResponse
    studyrecord_obj = models.StudyRecord.objects.get(id=stu_record_id)
    stuhomework_base_dir = '%s{sep}%s{sep}第%s节{sep}%s' % (settings.STU_HOMEWORK_DATA_URL,
                                                          studyrecord_obj.course_record.clazz,
                                                          studyrecord_obj.course_record.day_num,
                                                          studyrecord_obj.student.name,
                                                          )
    stuhomework_base_dir = stuhomework_base_dir.format(sep=os.sep)
    name=os.listdir(stuhomework_base_dir)[0]
    file = open(stuhomework_base_dir + os.sep + name, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="%s"' % name
    return response

templates/teacher/teacher_courserecord.html
{% extends 'blank.html' %}
{% load teacher_tags %}
{% block style %}
    <style>
        .stu_show{
           display:none;
        }




    </style>
{% endblock %}

{% block row-menus %}
    <ol class="breadcrumb">
        <i class="fa fa-home"></i><li><a href="{% url 'teacher_index' %}">首页</a></li>
        <li><i class="fa fa-book"></i><a href="javascript:void(0)">课程记录</a></li>

    </ol>


{% endblock  %}
{% block left-menu %}

{% endblock  %}


{% block page-content %}
    <div class="alert alert-info stu_show">

    </div>


    <div class="col-sm-12">
          <section class="panel">
              <header class="panel-heading">
                  xxx上课记录
                  <div class='col-lg-1 pull-right'>
                        <a href="./add"><button type="button" class="btn btn-success btn-xs ">添加一条数据</button></a>
                    </div>
              </header>
              <table class="table table-hover">
                  <thead>
                  <tr>
                      <th>#</th>
                      <th>学生姓名</th>
                      <th>所报班级</th>
                      <th>作业内容</th>
                      <th>应到人数</th>
                      <th>签到人数</th>
                      <th>迟到</th>
                      <th>缺勤</th>
                      <th>早退</th>
                      <th>请假</th>
                      <th>作业审批</th>
                      <th>上课老师</th>


                  </tr>
                  </thead>
                  <tbody>

                  {% for courserecord_obj in courserecord_obj_queryset %}
                      <tr>
                          <td>xx</td>
                          <td>第{{ courserecord_obj.day_num }}节</td>
                          <td>{{ courserecord_obj.outline }}</td>
                          <td>{{ courserecord_obj.home_title }}</td>
                          <td>{{ courserecord_obj.clazz.enrollment_set.all.count }}</td>
                          <td class="already  moreinfor">
                              <a href="javascrpt:void(0)">{% get_filter_stu_num courserecord_obj 0%}</a>
                              <span class="stu_show">签到:{% get_filter_stu_list courserecord_obj 0%}</span>
                          </td>


                          <td class="late moreinfor">
                              <a href="javascrpt:void(0)">{% get_filter_stu_num courserecord_obj 1%}</a>
                              <span class="stu_show">迟到:{% get_filter_stu_list courserecord_obj 1%}</span>

                          </td>


                          <td class="absenteeism moreinfor">
                              <a href="javascrpt:void(0)">{% get_filter_stu_num courserecord_obj 2%}</a>
                              <span class="stu_show">缺勤:{% get_filter_stu_list courserecord_obj 2%}</span>
                          </td>

                          <td class="leave-early moreinfor">
                              <a href="javascrpt:void(0)">{% get_filter_stu_num courserecord_obj 3%}</a>
                              <span class="stu_show">早退:{% get_filter_stu_list courserecord_obj 3%}</span>

                          </td>
                          <td class="ask-for-leave moreinfor">
                              <a href="javascrpt:void(0)">{% get_filter_stu_num courserecord_obj 4%}</a>
                              <span class="stu_show">请假:{% get_filter_stu_list courserecord_obj 4%}</span>
                          </td>


                          <td>xxx</td>
                          <td>{{ courserecord_obj.teachers.name }}</td>


                      </tr>

                  {% endfor %}






                  </tbody>
              </table>
          </section>
    </div>

{% endblock %}
{% block script %}
    <script>
        $('.moreinfor').on("click",'a',function () {

            $('.alert').removeClass('stu_show')
            $('.alert').empty()
            var infor=$(this).siblings('span').html()
            $('.alert').html(infor)




        })



    </script>

{% endblock %}

templates/teacher/teacher_courserecord_add.html
{% extends 'blank.html' %}
{% load teacher_tags %}
{% block style %}
    <style>
        .stu_show{
           display:none;
        }
        .point{
            cursor:pointer
        }



    </style>
{% endblock %}

{% block row-menus %}
    <ol class="breadcrumb"><i class="fa fa-home"></i><li><a href="{% url 'teacher_index' %}">首页</a></li>
        <li><i class="fa fa-book"></i><a href="./">课程记录</a></li>
    <li><i class="fa fa-add"></i>添加课程记录</li>
    </ol>


{% endblock  %}
{% block left-menu %}

{% endblock  %}


{% block page-content %}


    </div>


    <div class="col-sm-12">
          <section class="panel">
              {% if error %}
                  <div class="alert alert-block alert-danger fade in">
                      <strong>错误了!</strong> {{ error }}
                  </div>
              {% endif %}
              <header class="panel-heading">
                  添加{{ clazz_obj }}上课记录

              </header>

              <!--S_input form-->
          <form class='form-validate form-horizontal' action="" method="POST">
               {% for field in RCforms %}
                <div class="form-group" id="filed-list{{ field.name }}">

                        <label  class="col-sm-2 control-label" style="font-weight: normal">
                            {% if field.field.required %}
                                {{ field.label }}<span class="required">*</span>
                            {% else %}
                                {{ field.label }}
                            {% endif %}
                        </label>




                    <div class="col-sm-5" id="{{ field.name }}">
                        {{ field }}



                    </div>
                </div>

            {% endfor %}
           <button type="submit" class="btn btn-default">save</button>
              {% csrf_token %}
          </form>

              <!--E_input form-->

          </section>
    </div>

{% endblock %}
{% block script %}


{% endblock %}

templates/teacher/teacher_index.html
{% extends 'blank.html' %}
{% load teacher_tags %}
{% block row-menus %}
    <ol class="breadcrumb">
        <i class="fa fa-home"></i><li><a href="javascript:void(0)">首页</a></li>
    </ol>

{% endblock  %}
{% block left-menu %}

{% endblock  %}


{% block page-content %}
    <div class="col-sm-12">
          <section class="panel">
              <header class="panel-heading">
                  我的班级
              </header>
              <table class="table table-hover">
                  <thead>
                  <tr>
                      <th>#</th>
                      <th>班级名称</th>
                      <th>班级课程</th>
                      <th>开课日期</th>
                      <th>课程进度</th>
                      <th>上次课程大纲</th>


                  </tr>
                  </thead>
                  <tbody>

                  {% for class_obj in class_obj_queryset %}
                      <tr>
                          <td>xx</td>
                          <td><a href="/myadmin/crm/courserecord/{{ class_obj.id }}">{{ class_obj }}</a></td>
                          <td>{{ class_obj.course.name }}</td>
                          <td>{{ class_obj.start_data }}</td>
                          <td>已上{{ class_obj.courserecord_set.all.count }}节课</td>
                          <td>{{ class_obj.courserecord_set.last.outline }}</td>

                      </tr>
                  {% endfor %}






                  </tbody>
              </table>
          </section>
    </div>

{% endblock %}